### ISSUE TITLE
Why use &amp; to build http query?

### ISSUE THREAD

**Issue by josephting** [Ehesp/Steam-Login#5]
Is there any particular reason why `&amp;` is used instead of `&`?
https://github.com/Ehesp/Steam-Login/blob/master/src/Ehesp/SteamLogin/SteamLogin.php#L55

Loading the openid provider with &amp; as the separator will get redirected back to homepage and it doesn't work.

**Comment by Ehesp** [comment]
Uhh nope, never had issues with that myself but I do see potential problems. I can sort that.

**Comment by josephting** [comment]
Thanks.

I'm doing a PHP 302 redirect when user is accessing materials that requires authenticated users.
Replacing `&amp;` with `&` works though but just curious why do you need to use html entity in a URL.

**Comment by Ehesp** [comment]
https://github.com/Ehesp/Steam-Login/commit/df599925de7fa29cfdf199653cdc48737bd105e8

Yeah no idea haha, changed anyway.

**Comment by josephting** [comment]
Awesome. Appreciate it.
