### ISSUE TITLE
[Question] Laravel 5?

### ISSUE THREAD

**Issue by chriskonnertz** [Ehesp/Steam-Login#9]
Hello,

have you tested it with Laravel 5?

Regards

**Comment by Ehesp** [comment]
Hello,

I haven't no. Don't really use Laravel much at the moment. Shouldn't be hard to port across though!

**Comment by chriskonnertz** [comment]
Tested it. Did not test the View Composer thing but apart from that it's working fine.

**Comment by chriskonnertz** [comment]
Maybe you should add a note to let people know the package is supporting L5 as well.
